remote_theme: "mmistakes/minimal-mistakes"

# Minimal Mistakes settings
minimal_mistakes_skin: "default"
locale: "en-US"

author:
  name: "Max Gogats"
  bio: "Software Developer From Rockland County, NY"
  #avatar: "/assets/images/bio-photo.jpg"

# Sidebar settings
sidebar:
  title: "About Me"
  nav: "sidebar" # defined in _data/navigation.yml

# Navigation links
include:
  - _pages

