remote_theme: "mmistakes/minimal-mistakes"

# Minimal Mistakes settings
minimal_mistakes_skin: "default"
locale: "en-US"

# Sidebar settings
sidebar:
  title: "About Me"
  nav: "sidebar" # defined in _data/navigation.yml

author:
  name: "Max Gogats"
  bio: "Software Developer from Rockland County, NY"
  location: "Rockland County, NY"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MaxGogats"
    - label: "Email: mgogats@gmail.com"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mgogats@gmail.com"
    - label: "LinkedIn"
      url: "/linkedin.com/https://www.linkedin.com/in/max-gogats-a0181b14a/"

# Navigation links
include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache
